Using TensorFlow version 1.15.5
Checking dataset
Traceback (most recent call last):
  File "train.py", line 602, in <module>
    main()
  File "train.py", line 422, in main
    no_of_training_examples = sum(1 for line in open(train_file))
  File "train.py", line 422, in <genexpr>
    no_of_training_examples = sum(1 for line in open(train_file))
  File "/usr/lib64/python3.6/codecs.py", line 318, in decode
    def decode(self, input, final=False):
KeyboardInterrupt
